services:
  - type: web
    name: lumivo
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: AI_PROVIDER
        value: groq
      - key: AI_MODEL
        value: openai/gpt-oss-20b
      - key: CORS_ORIGINS
        value: "*"
      - key: GROQ_API_KEY
        sync: false
